### ISSUE TITLE
Uranime Plugin / No JSON object could be decoded

### ISSUE THREAD

**Issue by Nonobis** [groenlid/xdm-anime-plugin-repo#12]
I am trying to develop a indexer plugin for the anime mediatype ... after many try ...

i think i have a working plugin ... but i think, there is an issue with your Uranime api. It's not always sending a json to xdm.

INFO        2014-02-07 23:27:56.261116  
Tokyo Toshokan search for terms Strike+the+Blood in category 11.
INFO        2014-02-07 23:27:56.302751  
Found a Download([HorribleSubs] Strike the Blood - 17 [1080p].mkv) with the same url and we snatched it already. I'l get it again...
INFO        2014-02-07 23:27:56.432636  
Trying to snatch [HorribleSubs] Strike the Blood - 17 [1080p].mkv with Blackhole (Default)
INFO        2014-02-07 23:27:57.541171  
Download saved to Blackhole at /volume3/Torrent/Watch/Anime/Strike the Blood (XDM.3-1).torrent
DEBUG       2014-02-07 23:27:57.586894  
Blackhole (Default) snatched [HorribleSubs] Strike the Blood - 17 [1080p].mkv
DEBUG       2014-02-07 23:29:50.097833  
Checking status for Show(de.uranime.anime)[3] Strike the Blood
DEBUG       2014-02-07 23:29:50.102732  
Blackhole (Default) gave back status Unknown for Show(de.uranime.anime)[3] Strike the Blood on download None
DEBUG       2014-02-07 23:30:12.988799  
init paint on default root Anime(de.uranime.anime)[1] 
DEBUG       2014-02-07 23:30:13.730672  
init paint children on given root Show(de.uranime.anime)[3] Strike the Blood
DEBUG       2014-02-07 23:30:25.448209  
init update
DEBUG       2014-02-07 23:30:25.480304  
Getting Episode(de.uranime.anime)[22] Strike the Blood e17 Episode 17 with provider id 30804 on Uranime (Default)
DEBUG       2014-02-07 23:30:25.486357  
GETELEMENT with id: 30804
DEBUG       2014-02-07 23:30:26.038399  
getting info from http://groenlid.no-ip.org/api/animedetails/30804
ERROR       2014-02-07 23:30:26.048848  
Error during getElement of Uranime (Default) 
Error: No JSON object could be decoded

Traceback (most recent call last):
  File "/volume1/@appstore/xdm/share/XDM/xdm/plugins/meta.py", line 160, in outer
    return run(_args, *_kwargs)
  File "/usr/local/xdm/var/plugins/Provider/Uranime-de_uranime_uranime-0_3/uranime.py", line 66, in getElement
    self._createAnime(rootElement, mt, _request_show.json())
  File "/volume1/@appstore/xdm/share/XDM/site-packages/requests/models.py", line 629, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/usr/local/python/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

New value:False
Traceback:
Traceback (most recent call last):
  File "/volume1/@appstore/xdm/share/XDM/xdm/plugins/meta.py", line 160, in outer
    return run(_args, *_kwargs)
  File "/usr/local/xdm/var/plugins/Provider/Uranime-de_uranime_uranime-0_3/uranime.py", line 66, in getElement
    self._createAnime(rootElement, mt, _request_show.json())
  File "/volume1/@appstore/xdm/share/XDM/site-packages/requests/models.py", line 629, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/usr/local/python/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")

ValueError: No JSON object could be decoded
DEBUG       2014-02-07 23:30:26.052387  
sending ERROR with notifiers
INFO        2014-02-07 23:30:26.076690  
Uranime (Default) returned NO element
DEBUG       2014-02-07 23:30:28.289473  
init paint on default root Anime(de.uranime.anime)[1] 
DEBUG       2014-02-07 23:30:28.859554  
init paint children on given root Show(de.uranime.anime)[3] Strike the Blood

**Comment by groenlid** [comment]
Hmm.. seems that it's trying to fetch an anime with the id of 30804 which does not exist.
Episode 30804 does however, and is episode 17 associated with "Strike the blood".
I'll look into it :+1:

**Comment by seertenedos** [comment]
Also it should better handle when it does not find a match. maybe just return an empty json.  I am having a similar issue at the min when it passes an AID in by mistake instead of one of your IDs.

**Comment by Nonobis** [comment]
thkx for your comment, will wait for a fix an optimize my plugin for now :)

**Comment by groenlid** [comment]
> getting info from http://groenlid.no-ip.org/api/animedetails/30804
> ERROR 2014-02-07 23:30:26.048848

@lad1337, do you want to add some comments as to why xdm run's getelement with the episodeid?
Should getElement run different queries based on the type of element it gets here? https://github.com/groenlid/xdm-anime-plugin-repo/blob/master/Uranime/uranime.py#L51

**Comment by lad1337** [comment]
@groenlid yeah i added the (provider) tag to the call
when something is updated https://github.com/lad1337/XDM/blob/develop/xdm/tasks.py#L357
and when running from a media adder plugin
https://github.com/lad1337/XDM/blob/develop/xdm/tasks.py#L427

since this is a breaking change i would have notified you before it goes into master

> Should getElement run different queries based on the type of element it gets here?

i suppose... but why it was called with the element id i don't know

**Comment by seertenedos** [comment]
@groenlid just a heads up your search API is returning a http 502 error.  Bad Gateway

**Comment by groenlid** [comment]
@seertenedos I'm currently migrating the api to a new site which would explain the 502 error. The new api will be located at https://urani.me/api when I'm done, but for now you can find it http://urani.me:3000/api here.

**Comment by seertenedos** [comment]
thanks i will update my links
