### ISSUE TITLE
Issue adding series and you can only access a series via the picture not the name

### ISSUE THREAD

**Issue by seertenedos** [groenlid/xdm-anime-plugin-repo#7]
I added multiple anime series as you can see in the screen shot below but only the first series gets an image. Sadly since you can only access the details of the series by clicking on the picture i can't access the rest of the series. Clicking on the name does not work and also the name gets cut off instead of extending across the screen or wrapping.

Also when you add a series it takes you away from the search result screen but not to the series screen.

![image](https://f.cloud.github.com/assets/401009/1867711/f17189b0-7855-11e3-829c-e3aea7347bc5.png)

**Comment by seertenedos** [comment]
Further info on the missing images.
The original series i added the other day and it uses the url
/images/de.uranime.anime/Gundam%20Build%20Fighters%20%2844%29%20fanart_image.jpeg
but the new series below it uses urls like
http://urani.me/api/imageresize/5223133e-4a3c-47ce-966e-5bb7c0a8010b.jpg
what is interesting about these images is they are 398px x 0px hence the reason they are not visible as well as not been stored locally.

I am still investigating why you can't click the titles and why they get cut off but i assume it is partly the css

**Comment by seertenedos** [comment]
The show names been cut off relates to the style ".de-uranime-anime .Show h3" can the width property in this be increased from 29% to 60% that way most of the title fits as seen in the screen shot below.  Another option would be to allow the editing of the title displayed so it can be shortened into something that means the same thing to the user.

**Comment by seertenedos** [comment]
Also to fix the opening and closing of the Anime a one line change in the javascript seems to fix it.

Changing 
$('.de-uranime-anime').on('click', '.Show>.info img.poster, .Show>.info img.banner', function(){
to
$('.de-uranime-anime').on('click', '.Show>.info', function(){

Maybe changing the cursor on hover would be good as well but at least that fixes the open and close by been able to click anywhere on the line for that anime.

**Comment by groenlid** [comment]
i'll look into it after work today, but you can also send a pull request if you want.

**Comment by seertenedos** [comment]
I am new to git so i will give it a go for what i have worked out

**Comment by seertenedos** [comment]
Lad's stuff seems ot fix all this
